management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /olx-login
      exposure:
        include: '*'
        
server:
  port: 7001
  
spring.application.name: LOGIN-SERVICE
spring.config.import: configserver:http://localhost:9999
spring.zipkin.base-url: http://localhost:9411
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
   
